theme: minima
title: minima theme trial training
author: sumit nandi
email: sumitnandi@eaton.com
description: > # this means to ignore newlines until "baseurl:"
 github-pages traning bot and framework is a nice experience. 
 Small and focussed steps helps the training stay effective.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
